### ISSUE TITLE
Header text mixed-up

### ISSUE THREAD

**Issue by nliautaud** [sergeyfilimonov/sergeyfilimonov.com#1]
Hi, you got an issue with your intro text. It's more and more mixed-up during the animation.

![2019-02-28 23_41_25-sites rapides et pratiques pour des projets educatifs _ sergey filimonov](https://user-images.githubusercontent.com/761761/53603713-9a45e480-3bb2-11e9-8e72-ee19c0ec702a.png)

**Comment by sergeyfilimonov** [comment]
@nliautaud thanks! what browser and OS are you using?

**Comment by nliautaud** [comment]
Chrome 72.0.3626.121
Windows 10

**Comment by nliautaud** [comment]
Forget that, my chrome decided to translate on the fly your site and was breaking the effect. All good 👍

**Comment by sergeyfilimonov** [comment]
@nliautaud yeah, I didn't have a clue what was the reason :) Thanks for your time anyway!
